### ISSUE TITLE
Combine Dependabot PRs into a single one

### ISSUE THREAD

**Issue by Debakel** [Debakel/Dumpstermap#146]
https://github.com/hrvey/combine-prs-workflow

> This GitHub Workflow allows you to combine a number of PRs into a single one, by merging the branches for each PR into a new branch and opening a PR for it. Specifically, it was created to group Dependabot PRs together, but it is generic enough that it can be used with other services that create PRs with branch names that have a specific prefix (such as dependabot/{branchname} in the case of dependabot).

**Comment by Debakel** [comment]
Dependabot now supports grouped updates: https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/

```
# `dependabot.yml` file with customized Bundler configuration
# In this example, the name of the group is `dev-dependencies`, and
# only the `patterns` and `exclude-patterns` options are used.
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Create a group of dependencies to be updated together in one pull request
    groups:
       # Specify a name for the group, which will be used in pull request titles
       # and branch names
       dependencies:
          # Define patterns to include dependencies in the group (based on
          # dependency name)
          patterns:
            - "*"       # A wildcard that matches all dependencies in the package
                        # ecosystem. Note: using "*" may open a large pull request
```

Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
